export const postCardData = [
    {
        id: 1,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 1",
        content: "Lorem ipsum dolor sit amet 1, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 1.",
        status: "APPROVED",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 4,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 5,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 1,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 1",
        content: "Lorem ipsum dolor sit amet 1, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 1.",
        status: "APPROVED",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 4,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 5,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 1,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 1",
        content: "Lorem ipsum dolor sit amet 1, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 1.",
        status: "APPROVED",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 4,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 5,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 1,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 1",
        content: "Lorem ipsum dolor sit amet 1, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 1.",
        status: "APPROVED",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 4,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 5,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
];
