export const postCardData = [
    {
        id: 1,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 1",
        content: "Lorem ipsum dolor sit amet 1, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 1.",
        status: "APPROVED",
    },
    {
        id: 2,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Just Now",
        content: "Lorem ipsum dolor sit amet 2, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 2.",
        status: "APPROVED",
        image: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 3,
        username: "John Doe",
        timestamp: "1 day ago",
        title: "Lorem ipsum 3",
        content: "Lorem ipsum dolor sit amet 3, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 3.",
        status: "APPROVED",
    },
    {
        id: 4,
        username: "Jane Smith",
        timestamp: "1 week ago",
        title: "Lorem ipsum 4",
        content: "Lorem ipsum dolor sit amet 4, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 4.",
        status: "APPROVED",
    },
    {
        id: 5,
        username: "John Doe",
        timestamp: "1 month ago",
        title: "Lorem ipsum 5",
        content: "Lorem ipsum dolor sit amet 5, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 5.",
        status: "APPROVED",
    },
    {
        id: 6,
        username: "Jane Smith",
        timestamp: "1 year ago",
        title: "Lorem ipsum 6",
        content: "Lorem ipsum dolor sit amet 6, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 6.",
        status: "APPROVED",
    },
    {
        id: 7,
        username: "John Doe",
        timestamp: "1 minute ago",
        title: "Lorem ipsum 7",
        content: "Lorem ipsum dolor sit amet 7, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 7.",
        status: "APPROVED",
    },
    {
        id: 8,
        username: "Jane Smith",
        timestamp: "1 hour ago",
        title: "Lorem ipsum 8",
        content: "Lorem ipsum dolor sit amet 8, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 8.",
        status: "APPROVED",
    },
    {
        id: 9,
        username: "John Doe",
        timestamp: "1 day ago",
        title: "Lorem ipsum 9",
        content: "Lorem ipsum dolor sit amet 9, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 9.",
        status: "APPROVED",
    },
    {
        id: 10,
        username: "Jane Smith",
        timestamp: "2 days ago",
        title: "Lorem ipsum 10",
        content: "Lorem ipsum dolor sit amet 10, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 10.",
        status: "APPROVED",
    },
    {
        id: 11,
        username: "John Doe",
        timestamp: "2 weeks ago",
        title: "Lorem ipsum 11",
        content: "Lorem ipsum dolor sit amet 11, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 11.",
        status: "APPROVED",
    },
    {
        id: 12,
        username: "Jane Smith",
        timestamp: "2 months ago",
        title: "Lorem ipsum 12",
        content: "Lorem ipsum dolor sit amet 12, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 12.",
        status: "APPROVED",
    },
    {
        id: 13,
        username: "John Doe",
        timestamp: "2 years ago",
        title: "Lorem ipsum 13",
        content: "Lorem ipsum dolor sit amet 13, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 13.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 14,
        username: "Jane Smith",
        timestamp: "3 minutes ago",
        title: "Lorem ipsum 14",
        content: "Lorem ipsum dolor sit amet 14, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 14.",
        status: "APPROVED",
    },
    {
        id: 15,
        username: "John Doe",
        timestamp: "3 hours ago",
        title: "Lorem ipsum 15",
        content: "Lorem ipsum dolor sit amet 15, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 15.",
        status: "APPROVED",
    },
    {
        id: 16,
        username: "Jane Smith",
        timestamp: "3 days ago",
        title: "Lorem ipsum 16",
        content: "Lorem ipsum dolor sit amet 16, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 16.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 17,
        username: "John Doe",
        timestamp: "3 weeks ago",
        title: "Lorem ipsum 17",
        content: "Lorem ipsum dolor sit amet 17, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 17.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 18,
        username: "Jane Smith",
        timestamp: "3 months ago",
        title: "Lorem ipsum 18",
        content: "Lorem ipsum dolor sit amet 18, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 18.",
        status: "APPROVED",
    },
    {
        id: 19,
        username: "John Doe",
        timestamp: "3 years ago",
        title: "Lorem ipsum 19",
        content: "Lorem ipsum dolor sit amet 19, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 19.",
        status: "APPROVED",
    },
    {
        id: 20,
        username: "Jane Smith",
        timestamp: "4 minutes ago",
        title: "Lorem ipsum 20",
        content: "Lorem ipsum dolor sit amet 20, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 20.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 21,
        username: "Jane Smith",
        timestamp: "4 minutes ago",
        title: "Lorem ipsum 20",
        content: "Lorem ipsum dolor sit amet 20, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 20.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 22,
        username: "Jane Smith",
        timestamp: "4 minutes ago",
        title: "Lorem ipsum 20",
        content: "Lorem ipsum dolor sit amet 20, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 20.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 23,
        username: "Jane Smith",
        timestamp: "4 minutes ago",
        title: "Lorem ipsum 20",
        content: "Lorem ipsum dolor sit amet 20, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 20.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
    {
        id: 24,
        username: "Jane Smith",
        timestamp: "4 minutes ago",
        title: "Lorem ipsum 20",
        content: "Lorem ipsum dolor sit amet 20, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua 20.",
        status: "APPROVED",
        imageUrl: "https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w1200/2023/10/free-images.jpg",
    },
];
